# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: enforce-agent
description: |
  A helm chart for Chainguard's Enforce Agent.

  Documentation for the chart can be found [here](https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/alternative-installation-methods/).
type: application
version: 0.0.32
appVersion: v0.1.115
keywords:
  - chainguard
home: https://chainguard.dev
icon: "https://avatars.githubusercontent.com/u/87436699?s=200&v=4"
maintainers:
  - name: The Chainguard Team
    url: https://chainguard.dev
